### ISSUE TITLE
Cannot perform runtime binding on null reference

### ISSUE THREAD

**Issue by Puchaczov** [Puchaczov/Musoq#9]
query with dynamic attributes throws exception:

> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Query.Compiled_28.CompiledQuery.ComputeTable_r1ovw4_0_0(ISchemaProvider provider, CancellationToken token) in :line 33
   at Query.Compiled_28.CompiledQuery.Run(CancellationToken token) in :line 81
   at Musoq.Evaluator.CompiledQuery.Run(CancellationToken token)
   at Musoq.Server.Core.BackgroundServices.MusoqEvaluationService.<>c__DisplayClass3_0.<<RunEvaluation>b__0>d.MoveNext()

query is:
```
select 
   Sum(ToDecimal(Substring(price.text, 1, Length(price.text)))) 
  from #xml.file('E:\XmlTests\File.txt') 
  where parent.element = 'food' and price is not null group by 'fake'
```

I can overcome this limitation by using CTE:

```
with p as ( 
   select ToDecimal(Substring(price.text, 1, Length(price.text))) as price 
   from #xml.file('E:\XmlTests\File.txt') 
   where parent.element = 'food' and price is not null 
) select Sum(price) from p group by 'fake'
```

**Comment by Puchaczov** [comment]
I'm going to close this as I already fixed those kind of errors previously.
